"""empty message

Revision ID: 00582c68adc9
Revises: a6c6eee80b32
Create Date: 2020-05-05 21:10:55.852776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00582c68adc9'
down_revision = 'a6c6eee80b32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('User', 'auth_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('User', 'auth_id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
