"""empty message

Revision ID: 894e03fc1aee
Revises:
Create Date: 2020-05-03 16:27:19.893842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '894e03fc1aee'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    op.add_column('User', sa.Column('first_name', sa.String(), nullable=True))
    op.add_column('User', sa.Column('last_name', sa.String(), nullable=True))
    op.execute("UPDATE public.\"User\" SET first_name='test first name', last_name='test last name';")
    op.alter_column("User", "first_name", nullable=False)
    op.alter_column("User", "last_name", nullable=False)
    op.drop_column('User', 'name')


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('User', 'last_name')
    op.drop_column('User', 'first_name')
    # ### end Alembic commands ###
