"""empty message

Revision ID: 9d773c36ceb0
Revises: 
Create Date: 2020-05-01 18:41:58.024567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d773c36ceb0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('People', sa.Column('solved_boards_count', sa.String(), nullable=True))
    op.drop_column('People', 'catchphrase')
    op.add_column('SudokuBoard', sa.Column('solved_board', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('SudokuBoard', 'solved_board')
    op.add_column('People', sa.Column('catchphrase', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('People', 'solved_boards_count')
    # ### end Alembic commands ###
