"""empty message

Revision ID: a6c6eee80b32
Revises: b93ec1ca9c22
Create Date: 2020-05-05 18:07:09.816924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6c6eee80b32'
down_revision = 'b93ec1ca9c22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('auth_id', sa.Integer(), nullable=True))
    op.execute("UPDATE public.\"User\" SET auth_id=0;")
    op.alter_column('User', 'auth_id', nullable=False)
    op.drop_column('User', 'jwt')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('jwt', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('User', 'auth_id')
    # ### end Alembic commands ###
