"""empty message

Revision ID: b33c97e3b330
Revises: 00582c68adc9
Create Date: 2020-05-06 21:39:53.377739

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b33c97e3b330'
down_revision = '00582c68adc9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('SudokuBoard', sa.Column('solved_board_json', sa.String(), nullable=False))
    op.alter_column('SudokuBoard', 'board_json',
               existing_type=postgresql.ARRAY(sa.INTEGER()),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_column('SudokuBoard', 'solved_board')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('SudokuBoard', sa.Column('solved_board', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=False))
    op.alter_column('SudokuBoard', 'board_json',
               existing_type=sa.String(),
               type_=postgresql.ARRAY(sa.INTEGER()),
               existing_nullable=False)
    op.drop_column('SudokuBoard', 'solved_board_json')
    # ### end Alembic commands ###
