"""empty message

Revision ID: b93ec1ca9c22
Revises: 894e03fc1aee
Create Date: 2020-05-03 17:39:58.486099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b93ec1ca9c22'
down_revision = '894e03fc1aee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('jwt', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'jwt')
    # ### end Alembic commands ###
